### ISSUE TITLE
Do we need binarizer and why.

### ISSUE THREAD

**Issue by GurovNik** [Hydrospheredata/hydro-serving-example#26]
hydro-serving-example/models/binarizer/. The folder has some files of undefined nature. No description of what is it, where we need it. Should we delete it?

**Comment by KineticCookie** [comment]
The model serves two purposes:
1. To test manager contract inference of SparkML models
2. To test SparkML runtime images with our local SparkML inference implementation.

On the whole, it's more like a model for internal usage.
